import 'package:get/get.dart';

class MyLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ar': {
      'ok': 'تم',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      // شاشة المحادثة
      'type_message': 'اكتب رسالة...',
      'online': 'متصل',
      'typing': 'يكتب الآن...',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'message_copied': 'تم نسخ الرسالة',
      'delete_msg': 'حذف الرسالة',
      'delete_user': 'حذف المستخدم',
      'no_number': 'لا يوجد رقم',
      'user': 'مستخدم',
      'delete' : 'حذف',
      'block_user': 'حظر المستخدم',
      'block_group': 'حظر المجموعة',
      'user_name' : 'اسم المستخدم',
      'save_changes': 'حفظ التغييرات',
      'no_messages': 'لا توجد رسائل بعد',
      'confirm_delete': 'تأكيد الحذف',
      'are_you_sure': 'هل أنت متأكد من رغبتك في الحذف؟',
      'search': 'بحث',
      'group_name_hint':' اسم المجموعة',
      'members':'الأعضاء',

      // القائمة الجانبية والشاشات
      'title': 'تليجرام',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'pass': 'كلمة المرور',
      'register': 'إنشاء حساب جديد',
      'profile': 'الملف الشخصي',
      'new_group': 'مجموعة جديدة',
      'contacts': 'جهات الاتصال',
      'add_user': 'إضافة مستخدم',
      'calls': 'المكالمات',
      'saved_messages': 'الرسائل المحفوظة',
      'settings': 'الإعدادات',
      'exit': 'خروج',
      'no_chats': 'لا توجد محادثات بعد',
      'lang_name': 'English',

      // الإعدادات
      'account': 'الحساب',
      'bio': 'النبذة التعريفية',
      'username': 'اسم المستخدم',
      'settings_chat': 'إعدادات المحادثة',
      'settings_privacy': 'الخصوصية والأمان',
      'settings_notif': 'الإشعارات والأصوات',
      'settings_data': 'البيانات والتخزين',
      'settings_battery': 'توفير الطاقة',
      'settings_folders': 'مجلدات المحادثة',
      'settings_devices': 'الأجهزة',
      'settings_lang': 'اللغة',
      'help': 'المساعدة',
      'ask_question': 'اسأل سؤالاً',
      'telegram_faq': 'الأسئلة الشائعة',
      'privacy_policy': 'سياسة الخصوصية',
      
      // البروفايل والإضافة
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير (اختياري)',
      'phone': 'رقم الهاتف',
      'edit': 'تعديل البيانات',
      'change_pic': 'اضغط لتغيير الصورة',
      'success_update': 'تم تحديث البيانات بنجاح',
      'user_added': 'تمت إضافة جهة الاتصال بنجاح',
      'tap_to_change': 'اضغط للتغيير',
      'bio_text': 'مرحباً بك في تليجرام!',
    },
    'en': {
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      // Chat Screen
      'type_message': 'Type a message...',
      'online': 'online',
      'typing': 'typing...',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'message_copied': 'Message copied',
      'delete_msg': 'Delete Message',
      'delete_user': 'Delete User',
      'no_number': 'No Number',
      'user': 'User',
      'delete' : 'Delete',
      'block_user': 'Block User',
      'block_group': 'Block Group',
      'user_name' : 'Username',
      'save_changes': 'Save Changes',
      'no_messages': 'No messages yet',
      'confirm_delete': 'Confirm Delete',
      'are_you_sure': 'Are you sure you want to delete this?',
      'search': 'Search',
      'group_name_hint' :' Group Name',
      'members':'members',


      // Common Screens
      'title': 'Telegram',
      'login': 'Login',
      'email': 'Email',
      'pass': 'Password',
      'register': 'Create Account',
      'profile': 'My Profile',
      'new_group': 'New Group',
      'contacts': 'Contacts',
      'add_user': 'Add User',
      'calls': 'Calls',
      'saved_messages': 'Saved Messages',
      'settings': 'Settings',
      'exit': 'Exit',
      'no_chats': 'No chats yet',
      'lang_name': 'العربية',

      // Settings
      'account': 'Account',
      'bio': 'Bio',
      'username': 'Username',
      'settings_chat': 'Chat Settings',
      'settings_privacy': 'Privacy and Security',
      'settings_notif': 'Notifications and Sounds',
      'settings_data': 'Data and Storage',
      'settings_battery': 'Power Saving',
      'settings_folders': 'Chat Folders',
      'settings_devices': 'Devices',
      'settings_lang': 'Language',
      'help': 'Help',
      'ask_question': 'Ask a Question',
      'telegram_faq': 'Telegram FAQ',
      'privacy_policy': 'Privacy Policy',

      // Profile & Add User
      'first_name': 'First Name',
      'last_name': 'Last Name (Optional)',
      'phone': 'Phone Number',
      'edit': 'Edit Profile',
      'change_pic': 'Tap to change picture',
      'success_update': 'Profile updated successfully',
      'user_added': 'Contact added successfully',
      'tap_to_change': 'Tap to change',
      'bio_text': 'Welcome to Telegram!',

      
    },
  };
}